#!/bin/sh
# shellcheck disable=SC2154,SC1091,SC1090,SC2039
#  Copyright 2019 DefKorns (https://gitlab.com/DefKorns/language-selector/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# shellcheck disable=SC2086
source $mountpoint/etc/options_menu/network/scripts/om_vars
script_init

enable_cmds "RestoreUSB RestoreNAND"
[ ! -d "$usb_backup" ] && disable_cmds "RestoreUSB"
[ ! -d "$nand_backup" ] && disable_cmds "RestoreNAND"

usleep 50000 && $optionsMenu/options --commandPath $omNetworkCmds/ --scriptPath $omNetworkScripts --title "Network Options" &
