#!/bin/sh
# shellcheck disable=SC2154,SC1091,SC1090,SC2039
#  Copyright 2019 DefKorns (https://gitlab.com/DefKorns/om-wifi-backup/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# shellcheck disable=SC2086
source $mountpoint/etc/options_menu/scripts/om_functions
script_init

omNetwork="$optionsMenu/network"
omNetworkCmds="$omNetwork/commands"
omNetworkScripts="$omNetwork/scripts"
omWifiRestore="$omNetwork/restore"
omWifiRestoreCmds="$omWifiRestore/commands"
omWifiRestoreScripts="$omWifiRestore/scripts"

usb_backup="/media/data/wifi_backup"
nand_backup="$rootfs/etc/wifi_backup"
wpa_supplicant="/etc/wpa_supplicant"

disableRestoreUSB="$omNetworkCmds/_RestoreUsb"
disableRestoreNAND="$omNetworkCmds/_RestoreNand"
enableRestoreUSB="$omNetworkCmds/c0060_RestoreUsb"
enableRestoreNAND="$omNetworkCmds/c0050_RestoreNand"

backup_path="/media/data/wifi_backup"
dst="usb"
